apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: im-cluster-dev
requires:
  - path: ../im-manager/skaffold.yaml
  - path: ../im-web-client/skaffold.yaml
  - path: ../im-inspector/skaffold.yaml
