apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: im-cluster-dev
requires:
  - path: ../im-manager/skaffold.yaml
    activeProfiles:
      - name: dev
  - path: ../im-web-client/skaffold.yaml
  - path: ../im-inspector/skaffold.yaml
